name: PocketFactions
author: TheDiamondYT
description: A full featured Factions plugin for PocketMine-MP.
version: 1.0.1
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
main: TheDiamondYT\PocketFactions\PF
permissions:
  faction.bypass:
      default: op
